# busybox
LOCAL_PATH:= $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE := SetUp_MTP.sh
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/air/tools/TestPcTools/MTP_Tools
LOCAL_MODULE_STEM := SetUp_MTP.sh
LOCAL_MODULE_TAGS := debug
LOCAL_MODULE_CLASS := ETC
LOCAL_SRC_FILES := $(LOCAL_MODULE)
include $(BUILD_PREBUILT)

