# busybox
#include $(call all-subdir-makefiles)

LOCAL_PATH:= $(call my-dir)
include $(CLEAR_VARS)
LOCAL_MODULE := adb
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/air/AirSDK/tools
LOCAL_MODULE_STEM := adb
LOCAL_MODULE_TAGS := debug
LOCAL_MODULE_CLASS := ETC
LOCAL_SRC_FILES := $(LOCAL_MODULE)
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := aapt
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/air/AirSDK/tools
LOCAL_MODULE_STEM := aapt
LOCAL_MODULE_TAGS := debug
LOCAL_MODULE_CLASS := ETC
LOCAL_SRC_FILES := $(LOCAL_MODULE)
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := android
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/air/AirSDK/tools
LOCAL_MODULE_STEM := android
LOCAL_MODULE_TAGS := debug
LOCAL_MODULE_CLASS := ETC
LOCAL_SRC_FILES := $(LOCAL_MODULE)
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := apkbuilder
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/air/AirSDK/tools
LOCAL_MODULE_STEM := apkbuilder
LOCAL_MODULE_TAGS := debug
LOCAL_MODULE_CLASS := ETC
LOCAL_SRC_FILES := $(LOCAL_MODULE)
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := ddms
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/air/AirSDK/tools
LOCAL_MODULE_STEM := ddms
LOCAL_MODULE_TAGS := debug
LOCAL_MODULE_CLASS := ETC
LOCAL_SRC_FILES := $(LOCAL_MODULE)
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := dmtracedump
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/air/AirSDK/tools
LOCAL_MODULE_STEM := dmtracedump
LOCAL_MODULE_TAGS := debug
LOCAL_MODULE_CLASS := ETC
LOCAL_SRC_FILES := $(LOCAL_MODULE)
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := draw9patch
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/air/AirSDK/tools
LOCAL_MODULE_STEM := draw9patch
LOCAL_MODULE_TAGS := debug
LOCAL_MODULE_CLASS := ETC
LOCAL_SRC_FILES := $(LOCAL_MODULE)
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := emulator
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/air/AirSDK/tools
LOCAL_MODULE_STEM := emulator
LOCAL_MODULE_TAGS := debug
LOCAL_MODULE_CLASS := ETC
LOCAL_SRC_FILES := $(LOCAL_MODULE)
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := emulator-arm
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/air/AirSDK/tools
LOCAL_MODULE_STEM := emulator-arm
LOCAL_MODULE_TAGS := debug
LOCAL_MODULE_CLASS := ETC
LOCAL_SRC_FILES := $(LOCAL_MODULE)
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := emulator-x86
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/air/AirSDK/tools
LOCAL_MODULE_STEM := emulator-x86
LOCAL_MODULE_TAGS := debug
LOCAL_MODULE_CLASS := ETC
LOCAL_SRC_FILES := $(LOCAL_MODULE)
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := etc1tool
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/air/AirSDK/tools
LOCAL_MODULE_STEM := etc1tool
LOCAL_MODULE_TAGS := debug
LOCAL_MODULE_CLASS := ETC
LOCAL_SRC_FILES := $(LOCAL_MODULE)
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := hierarchyviewer
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/air/AirSDK/tools
LOCAL_MODULE_STEM := hierarchyviewer
LOCAL_MODULE_TAGS := debug
LOCAL_MODULE_CLASS := ETC
LOCAL_SRC_FILES := $(LOCAL_MODULE)
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := hprof-conv
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/air/AirSDK/tools
LOCAL_MODULE_STEM := hprof-conv
LOCAL_MODULE_TAGS := debug
LOCAL_MODULE_CLASS := ETC
LOCAL_SRC_FILES := $(LOCAL_MODULE)
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := lint
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/air/AirSDK/tools
LOCAL_MODULE_STEM := lint
LOCAL_MODULE_TAGS := debug
LOCAL_MODULE_CLASS := ETC
LOCAL_SRC_FILES := $(LOCAL_MODULE)
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := mksdcard
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/air/AirSDK/tools
LOCAL_MODULE_STEM := mksdcard
LOCAL_MODULE_TAGS := debug
LOCAL_MODULE_CLASS := ETC
LOCAL_SRC_FILES := $(LOCAL_MODULE)
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := monkeyrunner
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/air/AirSDK/tools
LOCAL_MODULE_STEM := monkeyrunner
LOCAL_MODULE_TAGS := debug
LOCAL_MODULE_CLASS := ETC
LOCAL_SRC_FILES := $(LOCAL_MODULE)
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := NOTICE.txt
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/air/AirSDK/tools
LOCAL_MODULE_STEM := NOTICE.txt
LOCAL_MODULE_TAGS := debug
LOCAL_MODULE_CLASS := ETC
LOCAL_SRC_FILES := $(LOCAL_MODULE)
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := source.properties
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/air/AirSDK/tools
LOCAL_MODULE_STEM := source.properties
LOCAL_MODULE_TAGS := debug
LOCAL_MODULE_CLASS := ETC
LOCAL_SRC_FILES := $(LOCAL_MODULE)
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := sqlite3
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/air/AirSDK/tools
LOCAL_MODULE_STEM := sqlite3
LOCAL_MODULE_TAGS := debug
LOCAL_MODULE_CLASS := ETC
LOCAL_SRC_FILES := $(LOCAL_MODULE)
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := traceview
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/air/AirSDK/tools
LOCAL_MODULE_STEM := traceview
LOCAL_MODULE_TAGS := debug
LOCAL_MODULE_CLASS := ETC
LOCAL_SRC_FILES := $(LOCAL_MODULE)
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := zipalign
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/air/AirSDK/tools
LOCAL_MODULE_STEM := zipalign
LOCAL_MODULE_TAGS := debug
LOCAL_MODULE_CLASS := ETC
LOCAL_SRC_FILES := $(LOCAL_MODULE)
include $(BUILD_PREBUILT)


include $(CLEAR_VARS)
LOCAL_MODULE := build.xml
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/air/AirSDK/tools/ant
LOCAL_MODULE_STEM := build.xml
LOCAL_MODULE_TAGS := debug
LOCAL_MODULE_CLASS := ETC
LOCAL_SRC_FILES := ant/$(LOCAL_MODULE)
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := NOTICE_ant.txt
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/air/AirSDK/tools/ant
LOCAL_MODULE_STEM := NOTICE.txt
LOCAL_MODULE_TAGS := debug
LOCAL_MODULE_CLASS := ETC
LOCAL_SRC_FILES := ant/$(LOCAL_MODULE)
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := pre_setup.xml
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/air/AirSDK/tools/ant
LOCAL_MODULE_STEM := pre_setup.xml
LOCAL_MODULE_TAGS := debug
LOCAL_MODULE_CLASS := ETC
LOCAL_SRC_FILES := ant/$(LOCAL_MODULE)
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := annotations.jar
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/air/AirSDK/tools/support
LOCAL_MODULE_STEM := annotations.jar
LOCAL_MODULE_TAGS := debug
LOCAL_MODULE_CLASS := ETC
LOCAL_SRC_FILES := support/$(LOCAL_MODULE)
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := android.el
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/air/AirSDK/tools/lib
LOCAL_MODULE_STEM := android.el
LOCAL_MODULE_TAGS := debug
LOCAL_MODULE_CLASS := ETC
LOCAL_SRC_FILES := lib/$(LOCAL_MODULE)
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := androidprefs.jar
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/air/AirSDK/tools/lib
LOCAL_MODULE_STEM := androidprefs.jar
LOCAL_MODULE_TAGS := debug
LOCAL_MODULE_CLASS := ETC
LOCAL_SRC_FILES := lib/$(LOCAL_MODULE)
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := anttasks.jar
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/air/AirSDK/tools/lib
LOCAL_MODULE_STEM := anttasks.jar
LOCAL_MODULE_TAGS := debug
LOCAL_MODULE_CLASS := ETC
LOCAL_SRC_FILES := lib/$(LOCAL_MODULE)
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := archquery.jar
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/air/AirSDK/tools/lib
LOCAL_MODULE_STEM := archquery.jar
LOCAL_MODULE_TAGS := debug
LOCAL_MODULE_CLASS := ETC
LOCAL_SRC_FILES := lib/$(LOCAL_MODULE)
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := asm-4.0.jar
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/air/AirSDK/tools/lib
LOCAL_MODULE_STEM := asm-4.0.jar
LOCAL_MODULE_TAGS := debug
LOCAL_MODULE_CLASS := ETC
LOCAL_SRC_FILES := lib/$(LOCAL_MODULE)
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := asm-tree-4.0.jar
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/air/AirSDK/tools/lib
LOCAL_MODULE_STEM := asm-tree-4.0.jar
LOCAL_MODULE_TAGS := debug
LOCAL_MODULE_CLASS := ETC
LOCAL_SRC_FILES := lib/$(LOCAL_MODULE)
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := build.template
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/air/AirSDK/tools/lib
LOCAL_MODULE_STEM := build.template
LOCAL_MODULE_TAGS := debug
LOCAL_MODULE_CLASS := ETC
LOCAL_SRC_FILES := lib/$(LOCAL_MODULE)
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := chimpchat.jar
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/air/AirSDK/tools/lib
LOCAL_MODULE_STEM := chimpchat.jar
LOCAL_MODULE_TAGS := debug
LOCAL_MODULE_CLASS := ETC
LOCAL_SRC_FILES := lib/$(LOCAL_MODULE)
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := common.jar
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/air/AirSDK/tools/lib
LOCAL_MODULE_STEM := common.jar
LOCAL_MODULE_TAGS := debug
LOCAL_MODULE_CLASS := ETC
LOCAL_SRC_FILES := lib/$(LOCAL_MODULE)
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := commons-codec-1.4.jar
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/air/AirSDK/tools/lib
LOCAL_MODULE_STEM := commons-codec-1.4.jar
LOCAL_MODULE_TAGS := debug
LOCAL_MODULE_CLASS := ETC
LOCAL_SRC_FILES := lib/$(LOCAL_MODULE)
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := commons-compress-1.0.jar
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/air/AirSDK/tools/lib
LOCAL_MODULE_STEM := commons-compress-1.0.jar
LOCAL_MODULE_TAGS := debug
LOCAL_MODULE_CLASS := ETC
LOCAL_SRC_FILES := lib/$(LOCAL_MODULE)
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := commons-logging-1.1.1.jar
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/air/AirSDK/tools/lib
LOCAL_MODULE_STEM := commons-logging-1.1.1.jar
LOCAL_MODULE_TAGS := debug
LOCAL_MODULE_CLASS := ETC
LOCAL_SRC_FILES := lib/$(LOCAL_MODULE)
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := ddmlib.jar
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/air/AirSDK/tools/lib
LOCAL_MODULE_STEM := ddmlib.jar
LOCAL_MODULE_TAGS := debug
LOCAL_MODULE_CLASS := ETC
LOCAL_SRC_FILES := lib/$(LOCAL_MODULE)
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := ddms.jar
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/air/AirSDK/tools/lib
LOCAL_MODULE_STEM := ddms.jar
LOCAL_MODULE_TAGS := debug
LOCAL_MODULE_CLASS := ETC
LOCAL_SRC_FILES := lib/$(LOCAL_MODULE)
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := ddmuilib.jar
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/air/AirSDK/tools/lib
LOCAL_MODULE_STEM := ddmuilib.jar
LOCAL_MODULE_TAGS := debug
LOCAL_MODULE_CLASS := ETC
LOCAL_SRC_FILES := lib/$(LOCAL_MODULE)
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := devices.xml
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/air/AirSDK/tools/lib
LOCAL_MODULE_STEM := devices.xml
LOCAL_MODULE_TAGS := debug
LOCAL_MODULE_CLASS := ETC
LOCAL_SRC_FILES := lib/$(LOCAL_MODULE)
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := draw9patch.jar
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/air/AirSDK/tools/lib
LOCAL_MODULE_STEM := draw9patch.jar
LOCAL_MODULE_TAGS := debug
LOCAL_MODULE_CLASS := ETC
LOCAL_SRC_FILES := lib/$(LOCAL_MODULE)
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := emma_ant.jar
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/air/AirSDK/tools/lib
LOCAL_MODULE_STEM := emma_ant.jar
LOCAL_MODULE_TAGS := debug
LOCAL_MODULE_CLASS := ETC
LOCAL_SRC_FILES := lib/$(LOCAL_MODULE)
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := emma_device.jar
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/air/AirSDK/tools/lib
LOCAL_MODULE_STEM := emma_device.jar
LOCAL_MODULE_TAGS := debug
LOCAL_MODULE_CLASS := ETC
LOCAL_SRC_FILES := lib/$(LOCAL_MODULE)
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := emma.jar
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/air/AirSDK/tools/lib
LOCAL_MODULE_STEM := emma.jar
LOCAL_MODULE_TAGS := debug
LOCAL_MODULE_CLASS := ETC
LOCAL_SRC_FILES := lib/$(LOCAL_MODULE)
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := guava-10.0.1.jar
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/air/AirSDK/tools/lib
LOCAL_MODULE_STEM := guava-10.0.1.jar
LOCAL_MODULE_TAGS := debug
LOCAL_MODULE_CLASS := ETC
LOCAL_SRC_FILES := lib/$(LOCAL_MODULE)
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := guavalib.jar
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/air/AirSDK/tools/lib
LOCAL_MODULE_STEM := guavalib.jar
LOCAL_MODULE_TAGS := debug
LOCAL_MODULE_CLASS := ETC
LOCAL_SRC_FILES := lib/$(LOCAL_MODULE)
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := hardware-properties.ini
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/air/AirSDK/tools/lib
LOCAL_MODULE_STEM := hardware-properties.ini
LOCAL_MODULE_TAGS := debug
LOCAL_MODULE_CLASS := ETC
LOCAL_SRC_FILES := lib/$(LOCAL_MODULE)
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := hierarchyviewer2.jar
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/air/AirSDK/tools/lib
LOCAL_MODULE_STEM := hierarchyviewer2.jar
LOCAL_MODULE_TAGS := debug
LOCAL_MODULE_CLASS := ETC
LOCAL_SRC_FILES := lib/$(LOCAL_MODULE)
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := hierarchyviewerlib.jar
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/air/AirSDK/tools/lib
LOCAL_MODULE_STEM := hierarchyviewerlib.jar
LOCAL_MODULE_TAGS := debug
LOCAL_MODULE_CLASS := ETC
LOCAL_SRC_FILES := lib/$(LOCAL_MODULE)
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := httpclient-4.1.1.jar
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/air/AirSDK/tools/lib
LOCAL_MODULE_STEM := httpclient-4.1.1.jar
LOCAL_MODULE_TAGS := debug
LOCAL_MODULE_CLASS := ETC
LOCAL_SRC_FILES := lib/$(LOCAL_MODULE)
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := httpcore-4.1.jar
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/air/AirSDK/tools/lib
LOCAL_MODULE_STEM := httpcore-4.1.jar
LOCAL_MODULE_TAGS := debug
LOCAL_MODULE_CLASS := ETC
LOCAL_SRC_FILES := lib/$(LOCAL_MODULE)
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := httpmime-4.1.1.jar
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/air/AirSDK/tools/lib
LOCAL_MODULE_STEM := httpmime-4.1.1.jar
LOCAL_MODULE_TAGS := debug
LOCAL_MODULE_CLASS := ETC
LOCAL_SRC_FILES := lib/$(LOCAL_MODULE)
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := jcommon-1.0.12.jar
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/air/AirSDK/tools/lib
LOCAL_MODULE_STEM := jcommon-1.0.12.jar
LOCAL_MODULE_TAGS := debug
LOCAL_MODULE_CLASS := ETC
LOCAL_SRC_FILES := lib/$(LOCAL_MODULE)
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := jfreechart-1.0.9.jar
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/air/AirSDK/tools/lib
LOCAL_MODULE_STEM := jfreechart-1.0.9.jar
LOCAL_MODULE_TAGS := debug
LOCAL_MODULE_CLASS := ETC
LOCAL_SRC_FILES := lib/$(LOCAL_MODULE)
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := jfreechart-1.0.9-swt.jar
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/air/AirSDK/tools/lib
LOCAL_MODULE_STEM := jfreechart-1.0.9-swt.jar
LOCAL_MODULE_TAGS := debug
LOCAL_MODULE_CLASS := ETC
LOCAL_SRC_FILES := lib/$(LOCAL_MODULE)
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := jsilver.jar
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/air/AirSDK/tools/lib
LOCAL_MODULE_STEM := jsilver.jar
LOCAL_MODULE_TAGS := debug
LOCAL_MODULE_CLASS := ETC
LOCAL_SRC_FILES := lib/$(LOCAL_MODULE)
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := jython.jar
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/air/AirSDK/tools/lib
LOCAL_MODULE_STEM := jython.jar
LOCAL_MODULE_TAGS := debug
LOCAL_MODULE_CLASS := ETC
LOCAL_SRC_FILES := lib/$(LOCAL_MODULE)
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libEGL_translator.so
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/air/AirSDK/tools/lib
LOCAL_MODULE_STEM := libEGL_translator.so
LOCAL_MODULE_TAGS := debug
LOCAL_MODULE_CLASS := ETC
LOCAL_SRC_FILES := lib/$(LOCAL_MODULE)
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libGLES_CM_translator.so
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/air/AirSDK/tools/lib
LOCAL_MODULE_STEM := libGLES_CM_translator.so
LOCAL_MODULE_TAGS := debug
LOCAL_MODULE_CLASS := ETC
LOCAL_SRC_FILES := lib/$(LOCAL_MODULE)
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libGLES_V2_translator.so
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/air/AirSDK/tools/lib
LOCAL_MODULE_STEM := libGLES_V2_translator.so
LOCAL_MODULE_TAGS := debug
LOCAL_MODULE_CLASS := ETC
LOCAL_SRC_FILES := lib/$(LOCAL_MODULE)
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libOpenglRender.so
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/air/AirSDK/tools/lib
LOCAL_MODULE_STEM := libOpenglRender.so
LOCAL_MODULE_TAGS := debug
LOCAL_MODULE_CLASS := ETC
LOCAL_SRC_FILES := lib/$(LOCAL_MODULE)
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := lint_api.jar
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/air/AirSDK/tools/lib
LOCAL_MODULE_STEM := lint_api.jar
LOCAL_MODULE_TAGS := debug
LOCAL_MODULE_CLASS := ETC
LOCAL_SRC_FILES := lib/$(LOCAL_MODULE)
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := lint_checks.jar
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/air/AirSDK/tools/lib
LOCAL_MODULE_STEM := lint_checks.jar
LOCAL_MODULE_TAGS := debug
LOCAL_MODULE_CLASS := ETC
LOCAL_SRC_FILES := lib/$(LOCAL_MODULE)
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := lint.jar
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/air/AirSDK/tools/lib
LOCAL_MODULE_STEM := lint.jar
LOCAL_MODULE_TAGS := debug
LOCAL_MODULE_CLASS := ETC
LOCAL_SRC_FILES := lib/$(LOCAL_MODULE)
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := lombok-ast-0.2.jar
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/air/AirSDK/tools/lib
LOCAL_MODULE_STEM := lombok-ast-0.2.jar
LOCAL_MODULE_TAGS := debug
LOCAL_MODULE_CLASS := ETC
LOCAL_SRC_FILES := lib/$(LOCAL_MODULE)
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := mkidentity.jar
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/air/AirSDK/tools/lib
LOCAL_MODULE_STEM := mkidentity.jar
LOCAL_MODULE_TAGS := debug
LOCAL_MODULE_CLASS := ETC
LOCAL_SRC_FILES := lib/$(LOCAL_MODULE)
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := monkeyrunner.jar
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/air/AirSDK/tools/lib
LOCAL_MODULE_STEM := monkeyrunner.jar
LOCAL_MODULE_TAGS := debug
LOCAL_MODULE_CLASS := ETC
LOCAL_SRC_FILES := lib/$(LOCAL_MODULE)
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := org.eclipse.core.commands_3.4.0.I20080509-2000.jar
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/air/AirSDK/tools/lib
LOCAL_MODULE_STEM := org.eclipse.core.commands_3.4.0.I20080509-2000.jar
LOCAL_MODULE_TAGS := debug
LOCAL_MODULE_CLASS := ETC
LOCAL_SRC_FILES := lib/$(LOCAL_MODULE)
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := org.eclipse.equinox.common_3.4.0.v20080421-2006.jar
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/air/AirSDK/tools/lib
LOCAL_MODULE_STEM := org.eclipse.equinox.common_3.4.0.v20080421-2006.jar
LOCAL_MODULE_TAGS := debug
LOCAL_MODULE_CLASS := ETC
LOCAL_SRC_FILES := lib/$(LOCAL_MODULE)
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := org.eclipse.jface_3.4.2.M20090107-0800.jar
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/air/AirSDK/tools/lib
LOCAL_MODULE_STEM := org.eclipse.jface_3.4.2.M20090107-0800.jar
LOCAL_MODULE_TAGS := debug
LOCAL_MODULE_CLASS := ETC
LOCAL_SRC_FILES := lib/$(LOCAL_MODULE)
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := osgi.jar
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/air/AirSDK/tools/lib
LOCAL_MODULE_STEM := osgi.jar
LOCAL_MODULE_TAGS := debug
LOCAL_MODULE_CLASS := ETC
LOCAL_SRC_FILES := lib/$(LOCAL_MODULE)
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := plugin.prop
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/air/AirSDK/tools/lib
LOCAL_MODULE_STEM := plugin.prop
LOCAL_MODULE_TAGS := debug
LOCAL_MODULE_CLASS := ETC
LOCAL_SRC_FILES := lib/$(LOCAL_MODULE)
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := proguard-project.txt
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/air/AirSDK/tools/lib
LOCAL_MODULE_STEM := proguard-project.txt
LOCAL_MODULE_TAGS := debug
LOCAL_MODULE_CLASS := ETC
LOCAL_SRC_FILES := lib/$(LOCAL_MODULE)
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := sdklib.jar
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/air/AirSDK/tools/lib
LOCAL_MODULE_STEM := sdklib.jar
LOCAL_MODULE_TAGS := debug
LOCAL_MODULE_CLASS := ETC
LOCAL_SRC_FILES := lib/$(LOCAL_MODULE)
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := sdkmanager.jar
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/air/AirSDK/tools/lib
LOCAL_MODULE_STEM := sdkmanager.jar
LOCAL_MODULE_TAGS := debug
LOCAL_MODULE_CLASS := ETC
LOCAL_SRC_FILES := lib/$(LOCAL_MODULE)
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := sdkstats.jar
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/air/AirSDK/tools/lib
LOCAL_MODULE_STEM := sdkstats.jar
LOCAL_MODULE_TAGS := debug
LOCAL_MODULE_CLASS := ETC
LOCAL_SRC_FILES := lib/$(LOCAL_MODULE)
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := sdkuilib.jar
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/air/AirSDK/tools/lib
LOCAL_MODULE_STEM := sdkuilib.jar
LOCAL_MODULE_TAGS := debug
LOCAL_MODULE_CLASS := ETC
LOCAL_SRC_FILES := lib/$(LOCAL_MODULE)
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := swing-worker-1.1.jar
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/air/AirSDK/tools/lib
LOCAL_MODULE_STEM := swing-worker-1.1.jar
LOCAL_MODULE_TAGS := debug
LOCAL_MODULE_CLASS := ETC
LOCAL_SRC_FILES := lib/$(LOCAL_MODULE)
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := swtmenubar.jar
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/air/AirSDK/tools/lib
LOCAL_MODULE_STEM := swtmenubar.jar
LOCAL_MODULE_TAGS := debug
LOCAL_MODULE_CLASS := ETC
LOCAL_SRC_FILES := lib/$(LOCAL_MODULE)
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := traceview.jar
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/air/AirSDK/tools/lib
LOCAL_MODULE_STEM := traceview.jar
LOCAL_MODULE_TAGS := debug
LOCAL_MODULE_CLASS := ETC
LOCAL_SRC_FILES := lib/$(LOCAL_MODULE)
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := snapshots.img
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/air/AirSDK/tools/lib/emulator
LOCAL_MODULE_STEM := snapshots.img
LOCAL_MODULE_TAGS := debug
LOCAL_MODULE_CLASS := ETC
LOCAL_SRC_FILES := lib/emulator/$(LOCAL_MODULE)
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := bios.bin
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/air/AirSDK/tools/lib/pc-bios
LOCAL_MODULE_STEM := bios.bin
LOCAL_MODULE_TAGS := debug
LOCAL_MODULE_CLASS := ETC
LOCAL_SRC_FILES := lib/pc-bios/$(LOCAL_MODULE)
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := vgabios-cirrus.bin
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/air/AirSDK/tools/lib/pc-bios
LOCAL_MODULE_STEM := vgabios-cirrus.bin
LOCAL_MODULE_TAGS := debug
LOCAL_MODULE_CLASS := ETC
LOCAL_SRC_FILES := lib/pc-bios/$(LOCAL_MODULE)
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := swt.jar
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/air/AirSDK/tools/lib/x86
LOCAL_MODULE_STEM := swt.jar
LOCAL_MODULE_TAGS := debug
LOCAL_MODULE_CLASS := ETC
LOCAL_SRC_FILES := lib/x86/$(LOCAL_MODULE)
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := swt_64.jar
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/air/AirSDK/tools/lib/x86_64
LOCAL_MODULE_STEM := swt.jar
LOCAL_MODULE_TAGS := debug
LOCAL_MODULE_CLASS := ETC
LOCAL_SRC_FILES := lib/x86_64/$(LOCAL_MODULE)
include $(BUILD_PREBUILT)

